config/routes.rb
Rails.application.routes.draw do
  get 'pets/index'
  get 'cats/index'
  get 'dogs/index'
  get 'pets/show'
  get 'pets/new'
  get 'pets/edit'
  root 'pets#index'

  resources :pets
  resources :dogs
  resources :cats

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :owners, as: :owneable
end

app/models/cat.rb
class Cat < Pet
end

app/models/corm.rb
class Corm < ActiveRecord::Base
  has_many :owners, as: :owneable
end

app/models/dog.rb
class Dog < Pet
end

app/models/fish.rb
class Fish < Pet
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :owneable, polymorphic: true
end

app/models/pet.rb
class Pet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < PetsController

  def index
  	@cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/dogs_controller.rb
class DogsController < PetsController

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
    @pet.type = params[:type]
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def create
    @pet = Pet.new(pet_params)
 
    if @pet.save
      redirect_to @pet
    else
      render 'new'
    end
  end

  def update
    @pet = Pet.find(params[:id])
 
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
 
    redirect_to pets_path
  end

  private
    def pet_params
      params.require(:pet).permit(:type, :name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_controller_helper.rb
module PetsControllerHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/cats/index.html.erb
<h1>The cats</h1>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
</thead>
  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.type %></td>
        <td><%= cat.name %></td>
        <td><%= cat.age %></td>
        <td><%= link_to 'Destroy', cat_path(cat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to 'New pets', new_pet_path %>
<%= link_to 'Back', pets_path, class: " label label-primary"%> 
</p>

app/views/cats/show.html.erb
<div class "container"> 
  <p>
    <%= @cat.type %>
  </p>
  <p>
    <%= @cat.name %>
  </p>
  <p>
    <%= @cat.age %>
  </p>
  <%= link_to 'Back', cats_path, class: " label label-primary"%> 
</div>

app/views/dogs/index.html.erb
<h1>The Dogs</h1>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
</thead>
  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.type %></td>
        <td><%= dog.name %></td>
        <td><%= dog.age %></td>
        <td><%= link_to 'Destroy', dog_path(dog), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to 'New pets', new_pet_path %>
<%= link_to 'Back', pets_path, class: " label label-primary"%>
</p>

app/views/dogs/show.html.erb
<div class "container"> 
  <p>
    <%= @dog.type %>
  </p>
  <p>
    <%= @dog.name %>
  </p>
  <p>
    <%= @dog.age %>
  </p>
  <%= link_to 'Back', dogs_path, class: " label label-primary"%> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>STIPolim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for @pet do |f| %>
 
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
      <h5>
        <%= pluralize(@pet.errors.count, "error") %> prohibited
        this pet from being saved:
      </h5>
      <ol>
        <% @pet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
      </div>
    </div>
  <% end %>

   
  <div class "container">
    <p>
      <%= select :pet, :type, ['Cat', 'Dog'] %>
    </p>
    <p>
      <%= f.label :name%><br>
      <%= f.text_field :name%>
    </p>
    <p>
      <%= f.label :age %><br>
      <%= f.text_field :age%>
    </p>
      <%= link_to 'Back', pets_path%>
      <%= f.submit%>
  <% end %>
</div>

app/views/pets/edit.html.erb
<center><h1>Edit pets</h1></center>
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>The Pets</h1>
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
</thead>
  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.type %></td>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= link_to 'Show', pet_path(pet) %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet_path(pet), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>
<%= link_to 'New pets', new_pet_path %>
</p>

app/views/pets/new.html.erb
<center><h1>New Pets</h1></center>
 <%= render 'form' %>

app/views/pets/show.html.erb
<div class "container"> 
  <p>
   
  <p>
      <%= @pet.type %>
  </p>
   
  <p>
      <%= @pet.name %>
  </p>

    <p>
      <%= @pet.age %>
  </p>
 
  <%= link_to 'Back', pets_path, class: " label label-primary"%> 
</div>